---

- name: get neighbor data
  hosts: all
  connection: local
  gather_facts: no


  tasks:

    - name: get neighbors
      nxos_get_neighbors: type=cdp host={{ inventory_hostname }}
      register: my_neighbors


    - name: get routing table for mgmt VRF
      nxos_command:
        type: show
        host: "{{ inventory_hostname }}"
        command: "show ip route vrf management"
      register: my_routes

    - name: Store to File
      template: src=templates/data.j2 dest=data/{{ inventory_hostname }}_gather_data.json

